Orders:
  Dig:
    Time: 1200
  Move:
    Time: 200
  NoDeath:
    Time: 2400
  Come:
    Time: 2400
  PlaceChooseYou:
    Time: 1200
  Kill:
    Time: 400
  Got:
    Time: 2400
  Knock:
    Time: 1800